name: CI With Build and Test

on:
    push:
        branches:
            - main

permissions:
    contents: read

jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: SSH 로 EC2 접속하기
              uses: appleboy/ssh-action@v1.0.3
              with:
                  host: ${{ secrets.EC2_HOST }}
                  username: ${{ secrets.EC2_USERNAME }}
                  key: ${{ secrets.EC2_PRIVATE_KEY }}
                  script_stop: true
                  script: |
                      sudo chown -R $USER:$USER /home/ubuntu/be/spring
                      git config --global --add safe.directory /home/ubuntube/spring
                      cd /home/ubuntu/be/spring
                      git pull origin main
                      ./gradlew clean build
                      cd ..
                      docker-compose up --build -d
